#!/usr/bin/env python3

from __future__ import annotations

import argparse
import io
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


DEFAULT_THRESHOLD_MB = 100
POINTER_PREFIX = b"version https://git-lfs.github.com/spec/v1\n"
POINTER_SCAN_LIMIT = 1024


@dataclass(frozen=True)
class TrackedEntry:
    path: str
    oid: str
    blob_size: int
    effective_size: int
    is_lfs_pointer: bool


def run_git(repo_root: Path, *args: str, input_bytes: bytes | None = None, check: bool = True) -> subprocess.CompletedProcess[bytes]:
    result = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        input=input_bytes,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and result.returncode != 0:
        message = result.stderr.decode("utf-8", "replace").strip()
        raise SystemExit(message or f"git {' '.join(args)} failed")
    return result


def load_tracked_paths(repo_root: Path) -> list[tuple[str, str]]:
    result = run_git(repo_root, "ls-files", "-s", "-z")
    entries: list[tuple[str, str]] = []
    for record in result.stdout.split(b"\0"):
        if not record:
            continue
        meta, raw_path = record.split(b"\t", 1)
        _mode, oid, stage = meta.decode("ascii").split()
        if stage != "0":
            continue
        entries.append((raw_path.decode("utf-8"), oid))
    return entries


def batch_blob_sizes(repo_root: Path, oids: list[str]) -> dict[str, int]:
    if not oids:
        return {}
    payload = "".join(f"{oid}\n" for oid in oids).encode("utf-8")
    result = run_git(repo_root, "cat-file", "--batch-check=%(objectname) %(objecttype) %(objectsize)", input_bytes=payload)
    sizes: dict[str, int] = {}
    for line in result.stdout.decode("utf-8").splitlines():
        oid, obj_type, size_text = line.split()
        if obj_type == "blob":
            sizes[oid] = int(size_text)
    return sizes


def parse_lfs_size(content: bytes) -> int | None:
    if not content.startswith(POINTER_PREFIX):
        return None
    for line in content.splitlines():
        if line.startswith(b"size "):
            return int(line.split()[1])
    return None


def batch_pointer_sizes(repo_root: Path, candidate_oids: list[str]) -> dict[str, int]:
    if not candidate_oids:
        return {}
    payload = "".join(f"{oid}\n" for oid in candidate_oids).encode("utf-8")
    result = run_git(repo_root, "cat-file", "--batch", input_bytes=payload)
    output = io.BytesIO(result.stdout)
    pointer_sizes: dict[str, int] = {}
    while True:
        header = output.readline()
        if not header:
            break
        oid, obj_type, size_text = header.decode("utf-8").strip().split()
        size = int(size_text)
        content = output.read(size)
        output.read(1)
        if obj_type != "blob":
            continue
        lfs_size = parse_lfs_size(content)
        if lfs_size is not None:
            pointer_sizes[oid] = lfs_size
    return pointer_sizes


def load_tracked_entries(repo_root: Path) -> list[TrackedEntry]:
    tracked_paths = load_tracked_paths(repo_root)
    unique_oids = sorted({oid for _, oid in tracked_paths})
    blob_sizes = batch_blob_sizes(repo_root, unique_oids)
    pointer_candidates = [oid for oid, size in blob_sizes.items() if size <= POINTER_SCAN_LIMIT]
    pointer_sizes = batch_pointer_sizes(repo_root, pointer_candidates)

    entries: list[TrackedEntry] = []
    for path, oid in tracked_paths:
        blob_size = blob_sizes[oid]
        if oid in pointer_sizes:
            effective_size = pointer_sizes[oid]
            is_pointer = True
        else:
            effective_size = blob_size
            is_pointer = False
        entries.append(
            TrackedEntry(
                path=path,
                oid=oid,
                blob_size=blob_size,
                effective_size=effective_size,
                is_lfs_pointer=is_pointer,
            )
        )
    return entries


def escape_gitattributes_path(path: str) -> str:
    escaped: list[str] = []
    for char in path:
        if char in {"\\", " ", "\t", "*", "?", "[", "]"}:
            escaped.append("\\")
        escaped.append(char)
    return "".join(escaped)


def render_gitattributes(paths: list[str], threshold_mb: int) -> str:
    lines = [
        "# Auto-generated by scripts/sync_git_lfs_by_size.py",
        f"# Only tracked files larger than {threshold_mb} MB use Git LFS.",
        "",
    ]
    lines.extend(
        f"/{escape_gitattributes_path(path)} filter=lfs diff=lfs merge=lfs -text"
        for path in sorted(paths)
    )
    return "\n".join(lines).rstrip() + "\n"


def write_gitattributes(repo_root: Path, content: str) -> bool:
    gitattributes_path = repo_root / ".gitattributes"
    existing = gitattributes_path.read_text(encoding="utf-8") if gitattributes_path.exists() else ""
    if existing == content:
        return False
    gitattributes_path.write_text(content, encoding="utf-8")
    return True


def has_git_lfs(repo_root: Path) -> bool:
    result = run_git(repo_root, "lfs", "version", check=False)
    return result.returncode == 0


def staged_paths(repo_root: Path) -> set[str]:
    result = run_git(repo_root, "diff", "--cached", "--name-only", "-z", "--diff-filter=AM")
    return {path.decode("utf-8") for path in result.stdout.split(b"\0") if path}


def restage_large_files(repo_root: Path, entries_by_path: dict[str, TrackedEntry], large_paths: set[str], attrs_changed: bool) -> None:
    staged = staged_paths(repo_root)
    if not staged and not attrs_changed:
        return

    to_convert = sorted(
        path for path in staged
        if path in large_paths and not entries_by_path[path].is_lfs_pointer
    )

    if to_convert and not has_git_lfs(repo_root):
        joined = "\n".join(f"- {path}" for path in to_convert)
        raise SystemExit(
            "git-lfs is not installed, so newly staged files larger than 100 MB cannot be re-added as LFS objects.\n"
            "Install git-lfs and re-run the commit.\n"
            f"Affected files:\n{joined}"
        )

    if attrs_changed:
        run_git(repo_root, "add", ".gitattributes")
    if to_convert:
        run_git(repo_root, "add", "--", *to_convert)


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Git LFS tracking rules from a size threshold.")
    parser.add_argument("--threshold-mb", type=int, default=DEFAULT_THRESHOLD_MB)
    parser.add_argument("--write", action="store_true", help="Write the generated rules to .gitattributes.")
    parser.add_argument(
        "--restage-staged",
        action="store_true",
        help="Stage .gitattributes and re-add staged large files so LFS filters can apply.",
    )
    args = parser.parse_args()

    repo_root_text = run_git(Path.cwd(), "rev-parse", "--show-toplevel").stdout.decode("utf-8").strip()
    repo_root = Path(repo_root_text)
    threshold_bytes = args.threshold_mb * 1024 * 1024

    entries = load_tracked_entries(repo_root)
    entries_by_path = {entry.path: entry for entry in entries}
    large_paths = {entry.path for entry in entries if entry.effective_size > threshold_bytes}
    content = render_gitattributes(sorted(large_paths), args.threshold_mb)

    attrs_changed = False
    if args.write:
        attrs_changed = write_gitattributes(repo_root, content)
    else:
        sys.stdout.write(content)

    if args.restage_staged:
        restage_large_files(repo_root, entries_by_path, large_paths, attrs_changed)

    if args.write:
        state = "updated" if attrs_changed else "already up to date"
        print(f".gitattributes {state}; tracking {len(large_paths)} file(s) above {args.threshold_mb} MB.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())